### ISSUE TITLE
Add temperature, topP to GenerateTextRequest

### ISSUE THREAD

**Issue by r2d4** [r2d4/react-llm#1]
https://github.com/r2d4/react-llm/blob/main/packages/headless/src/worker/llm.ts#L227 also takes in two additional parameters temperature and topP which are currently hardcoded https://github.com/r2d4/react-llm/blob/main/packages/headless/src/worker/llm.ts#L330

These should be added to the GenerateTextRequest https://github.com/r2d4/react-llm/blob/main/packages/headless/src/types/worker_message.ts#L13-L18

**Comment by lxfater** [comment]
I am more than willing to help resolve this issue. However, when I ran this project, I noticed that it is using my integrated graphics card for computation. Is there any way to make it use my dedicated graphics card? I hope I can get this project up and running. Thank you for your assistance.

**Comment by lxfater** [comment]
I have initiated a pull request. #2  I might not have fully understood all your code. If there are any issues with the code I submitted, please feel free to reach out to me at your earliest convenience.
